---
title: "delete_seqs_suggested_by_sativa"
author: "Douglas Yu" Modified by "Yinqiu Ji"
date: "11/05/2019" Modified date "2023Feb"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd("~/src/screenforbio-mbc-23GLG")
```

```{r}
library(readr)
library(tidyverse)
```

Programming note:  readr can import only if the first set of lines is skipped and the column names are provided
```{r delete lrRNA sequences that sativa flags as wrong at family and above}
MIDORI_lrRNA.Tetropoda <- read_delim("~/src/screenforbio-mbc-23GLG/MIDORI_lrRNA.Tetropoda_sativa/MIDORI_lrRNA.Tetropoda.mis",
                           "\t", 
                           escape_double = FALSE, 
                           trim_ws = TRUE, 
                           skip = 5, 
                           col_names = c("SeqID", "MislabeledLevel","OriginalLabel","ProposedLabel",
"Confidence","OriginalTaxonomyPath","ProposedTaxonomyPath","PerRankConfidence"))
# the key is to skip the first set of lines
names(MIDORI_lrRNA.Tetropoda)
MIDORI_lrRNA.Tetropoda_sep <- MIDORI_lrRNA.Tetropoda %>% 
    tidyr::separate(PerRankConfidence, sep = ";", into = c("domain_conf", "phylum_conf", "class_conf", "order_conf", "family_conf", "genus_conf", "species_conf"), remove = FALSE)

# save file with SeqIDs of all sequences where sativa disagrees with its taxonomic designation at the ranks of class, order, family, or subtribe. To do this, i choose all rows where MislabeledLevel != Genus or Species. These are sequences to delete.
unique(MIDORI_lrRNA.Tetropoda_sep$MislabeledLevel) # use this to determine which levels to keep. Here, keep c("Class", "Order","Family")
MIDORI.Tetropoda_locus.mis_to_delete <- MIDORI_lrRNA.Tetropoda_sep %>% 
    filter(MislabeledLevel %in% c("Class", "Order","Family")) %>% 
    select(SeqID)
write_tsv(MIDORI.Tetropoda_locus.mis_to_delete, "~/src/screenforbio-mbc-23GLG/MIDORI_lrRNA.Tetropoda_sativa/MIDORI_lrRNA.Tetropoda.mis_to_delete", col_names = FALSE)
```

```{r delete srRNA sequences that sativa flags as wrong at family and above}
MIDORI_srRNA.Tetropoda <- read_delim("~/src/screenforbio-mbc-23GLG/MIDORI_srRNA.Tetropoda_sativa/MIDORI_srRNA.Tetropoda.mis", 
                           "\t", 
                           escape_double = FALSE, 
                           trim_ws = TRUE, 
                           skip = 5, 
                           col_names = c("SeqID", "MislabeledLevel","OriginalLabel","ProposedLabel","Confidence","OriginalTaxonomyPath","ProposedTaxonomyPath","PerRankConfidence"))
# the key is to skip the first set of lines
names(MIDORI_srRNA.Tetropoda)
MIDORI_srRNA.Tetropoda_sep <- MIDORI_srRNA.Tetropoda %>% 
    tidyr::separate(PerRankConfidence, sep = ";", into = c("domain_conf", "phylum_conf", "class_conf", "order_conf", "family_conf", "genus_conf", "species_conf"), remove = FALSE)

# save file with SeqIDs of all sequences where sativa disagrees with its taxonomic designation at the ranks of class, order, family, or subtribe. To do this, i choose all rows where MislabeledLevel != Genus or Species. These are sequences to delete.
unique(MIDORI_srRNA.Tetropoda_sep$MislabeledLevel) # use this to determine which levels to keep. Here, keep c("Class", "Order","Epifamily","Family")
MIDORI.Tetropoda_locus.mis_to_delete <- MIDORI_srRNA.Tetropoda_sep %>% 
    filter(MislabeledLevel %in% c("Class", "Order","Epifamily","Family")) %>% 
    select(SeqID)
write_tsv(MIDORI.Tetropoda_locus.mis_to_delete, "~/src/screenforbio-mbc-23GLG/MIDORI_srRNA.Tetropoda_sativa/MIDORI_srRNA.Tetropoda.mis_to_delete", col_names = FALSE)
```

```{r delete lrRNA sequences that sativa flags as wrong at family and above}
MIDORI_lrRNA.Teleostei <- read_delim("~/src/screenforbio-mbc-23GLG/MIDORI_lrRNA.Teleostei_sativa/MIDORI_lrRNA.Teleostei.mis",
                           "\t", 
                           escape_double = FALSE, 
                           trim_ws = TRUE, 
                           skip = 5, 
                           col_names = c("SeqID", "MislabeledLevel","OriginalLabel","ProposedLabel",
"Confidence","OriginalTaxonomyPath","ProposedTaxonomyPath","PerRankConfidence"))
# the key is to skip the first set of lines
names(MIDORI_lrRNA.Teleostei)
MIDORI_lrRNA.Teleostei_sep <- MIDORI_lrRNA.Teleostei %>% 
    tidyr::separate(PerRankConfidence, sep = ";", into = c("domain_conf", "phylum_conf", "class_conf", "order_conf", "family_conf", "genus_conf", "species_conf"), remove = FALSE)

# save file with SeqIDs of all sequences where sativa disagrees with its taxonomic designation at the ranks of class, order, family, or subtribe. To do this, i choose all rows where MislabeledLevel != Genus or Species. These are sequences to delete.
unique(MIDORI_lrRNA.Teleostei_sep$MislabeledLevel) # use this to determine which levels to keep. Here, keep c("Class", "Order","Family")
MIDORI.Teleostei_locus.mis_to_delete <- MIDORI_lrRNA.Teleostei_sep %>% 
    filter(MislabeledLevel %in% c("Class", "Order","Family")) %>% 
    select(SeqID)
write_tsv(MIDORI.Teleostei_locus.mis_to_delete, "~/src/screenforbio-mbc-23GLG/MIDORI_lrRNA.Teleostei_sativa/MIDORI_lrRNA.Teleostei.mis_to_delete", col_names = FALSE)
```

```{r delete srRNA sequences that sativa flags as wrong at family and above}
MIDORI_srRNA.Teleostei <- read_delim("~/src/screenforbio-mbc-23GLG/MIDORI_srRNA.Teleostei_sativa/MIDORI_srRNA.Teleostei.mis", 
                           "\t", 
                           escape_double = FALSE, 
                           trim_ws = TRUE, 
                           skip = 5, 
                           col_names = c("SeqID", "MislabeledLevel","OriginalLabel","ProposedLabel","Confidence","OriginalTaxonomyPath","ProposedTaxonomyPath","PerRankConfidence"))
# the key is to skip the first set of lines
names(MIDORI_srRNA.Teleostei)
MIDORI_srRNA.Teleostei_sep <- MIDORI_srRNA.Teleostei %>% 
    tidyr::separate(PerRankConfidence, sep = ";", into = c("domain_conf", "phylum_conf", "class_conf", "order_conf", "family_conf", "genus_conf", "species_conf"), remove = FALSE)

# save file with SeqIDs of all sequences where sativa disagrees with its taxonomic designation at the ranks of class, order, family, or subtribe. To do this, i choose all rows where MislabeledLevel != Genus or Species. These are sequences to delete.
unique(MIDORI_srRNA.Teleostei_sep$MislabeledLevel) # use this to determine which levels to keep. Here, keep c("Class", "Order","Epifamily","Family")
MIDORI.Teleostei_locus.mis_to_delete <- MIDORI_srRNA.Teleostei_sep %>% 
    filter(MislabeledLevel %in% c("Class", "Order","Epifamily","Family")) %>% 
    select(SeqID)
write_tsv(MIDORI.Teleostei_locus.mis_to_delete, "~/src/screenforbio-mbc-23GLG/MIDORI_srRNA.Teleostei_sativa/MIDORI_srRNA.Teleostei.mis_to_delete", col_names = FALSE)
```

